"""Add Google OAuth Token table

Revision ID: a1b2c3d4e5f6
Revises: e7a17a8acf4c
Create Date: 2025-09-15 14:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "e7a17a8acf4c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if "google_oauth_token" not in inspector.get_table_names():
        op.create_table(
            "google_oauth_token",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("uid", sa.Integer(), nullable=False),
            sa.Column("access_token", sa.Text(), nullable=False),
            sa.Column("refresh_token", sa.Text(), nullable=True),
            sa.Column("token_type", sa.String(length=50), nullable=True, default="Bearer"),
            sa.Column("expires_at", sa.DateTime(), nullable=True),
            sa.Column("scope", sa.Text(), nullable=True),
            sa.Column("created_at", sa.DateTime(), nullable=False, server_default=func.now()),
            sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=func.now(), onupdate=func.now()),
            sa.ForeignKeyConstraint(["uid"], ["user.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("uid"),
            mysql_charset="utf8mb4",
            mysql_engine="InnoDB",
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("google_oauth_token")
    # ### end Alembic commands ###